name: CI

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
           fetch-depth: 0
      
      # Runs a single command using the runners shell
      - name: Setup Java 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      #- name: Cache Docker images
      #  uses: satackey/action-docker-layer-caching@v0.0.11
      #  # Ignore the failure of a step and avoid terminating the job.
      #  continue-on-error: true

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn clean install
        
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - name: Build and analyze 2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=404notfoundpk_ISW2-jcs
